### ISSUE TITLE
Support`import A as B` syntax

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1271]
Make sure that 
- `B` is a defined variable, `A` is not
- `A.jl` is installed by PlutoPkg, not `B.jl`
- the regex in the frontend can handle it when multiple imports are combined

https://docs.julialang.org/en/v1/manual/modules/#Renaming-with-as

First time contributors: this is an issue about ExpressionExplorer, see the source code and tests with that name to learn more. It should be a good first issue, as it does not require an overview understanding of how Pluto works.

**Comment by Pangoraw** [comment]
done with #1606 and cie

**Comment by fonsp** [comment]
It's still not working after re-evaluation:

https://user-images.githubusercontent.com/6933510/144224773-2c81c0ea-6902-475b-82ae-1db89ed99797.mov

**Comment by Pangoraw** [comment]
For the julia side: https://github.com/JuliaLang/julia/issues/43290

**Comment by Pangoraw** [comment]
This works in the master branch of julia and in julia 1.8 preview (also backported to future julia 1.7 and 1.6 releases)!

![image](https://user-images.githubusercontent.com/9824244/160291612-a4a1b4e9-152f-4233-a522-f86cd9377c9f.png)
