### ISSUE TITLE
Live docs - include prefixed module in search term

### ISSUE THREAD

**Issue by staticfloat** [fonsp/Pluto.jl#239]
I tried to get the live docs for `CSV.File`, as shown in [the excellent JuliaCon 2020 talk](https://youtu.be/IAF8DjrQSSk), but unfortunately, it doesn't work for me:

![image](https://user-images.githubusercontent.com/130920/88966998-0b833e80-d262-11ea-8949-9d798648eb72.png)

This is running Pluto `v0.11.1` on Julia 1.4.2 on macOS.

**Comment by fonsp** [comment]
Yeah you have to select (with your mouse) the whole expression `CSV.File`, if the cursor is on top of `File`, it will only search for that. But let's fix that!

**Comment by staticfloat** [comment]
Hmmm, that doesn't seem to be working for me either:

![image](https://user-images.githubusercontent.com/130920/88978722-172c3080-d275-11ea-9340-2032fce4f1ab.png)

**Comment by fonsp** [comment]
Thanks! I'll look into it

**Comment by fonsp** [comment]
Also write to #111 if you have suggestions!

**Comment by fonsp** [comment]
Fixed! Will be released soon

sorry it took a while :)

**Comment by fonsp** [comment]
testset:
https://github.com/fonsp/Pluto.jl/commit/d402723ae1a49d84636499a1269d301190d9cab5#diff-e5dfd5312bb88144a97d32e9a036f118R74

**Comment by mapclyps** [comment]
For me the original issue is still there in Pluto 0.11.10. 

I think it is when the function is not exported, the documentation is not showing up. As in the `CSV.File` in the original issue where `File` is not exported. The test passes since `Base.sqrt` is exported as `sqrt`

**Comment by fonsp** [comment]
Aha, it works, but you need to select the whole phrase `CSV.File`. If you place your cursor at `File`, then it will only search for `File`.

But this should be detected

**Comment by mapclyps** [comment]
> Aha, it works, but you need to select the whole phrase `CSV.File`. If you place your cursor at `File`, then it will only search for `File`.
> 
> But this should be detected

Oh yes it works indeed with selecting the whole expression. I should have tried that. 
Recognition of the dot syntax for the live docs display would be really nice!

**Comment by fonsp** [comment]
It now detects the prefixed module while typing!
