### ISSUE TITLE
kwagrs for macro calls

### ISSUE THREAD

**Issue by mcmcgrath13** [fonsp/Pluto.jl#252]
I started working on supporting rendering of the vega and vegalite mime types (nominally working!), but I ran into the below issue when trying to have two plots:

![image](https://user-images.githubusercontent.com/24885580/89247318-14b23980-d5db-11ea-9d24-3c74aac1553b.png)

I ran `@macroexpand` on the expressions and got:
```julia
:(dataset("cars") |> (VegaLite.VegaLite).VLSpec(VegaLite.convert_frag_tree_to_dict(VegaLite.fix_shortcut_level_spec((VegaLite.VLFrag)(VegaLite.Any[:point], VegaLite.OrderedDict{VegaLite.String, VegaLite.Any}("x" => :Horsepower, "y" => :Miles_per_Gallon))))))
```

I'm not sure why it's registering the x and y as variables in the main scope.  Any idea what's happening here?

**Comment by fonsp** [comment]
Thanks!

Pluto works by figuring out the set of _assigned variables_ and _referenced variables_ for each cell. If one cell references a symbol `x`, and and another assigns to `x`, then that is a reactive link between them.

In this case, a bug in the analysis treats the keyword argument `x=:asdf` as an assignment. I wrote a special case for function calls, but not for macros.

A more general problem is that Pluto doesn't understand macros (#196), but luckily this macro can be parsed as if it is a function call - it does not need to be expanded for the syntax analysis to work.

**Comment by fonsp** [comment]
Should be fixed now, can you try again?>

**Comment by fonsp** [comment]
You need to run the master branch of Pluto

**Comment by mcmcgrath13** [comment]
I'm using the master branch of Pluto, but still seeing the same issue:

![image](https://user-images.githubusercontent.com/24885580/91051678-710ee480-e5ee-11ea-9079-f44c65ad76eb.png)

**Comment by fonsp** [comment]
This can't be fixed without expanding the macro (#196):
`@f(x=y)`
and
`@f x = y`
produce the same `Expr`, and something that looks like the second expression should be recognised as an assignment to `x`. (`@benchmark x = y` for example)

Try using a semicolon:
```julia
@vlplot(
	:a;
	x = :b,
	...
)
```

**Comment by fonsp** [comment]
This has been fixed by #670
